//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dstempModel", "dept_emp_ibfk_2", "departments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.department), "dept_emp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.dept_emp), true)]
[assembly: EdmRelationshipAttribute("dstempModel", "dept_manager_ibfk_2", "departments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.department), "dept_manager", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.dept_manager), true)]
[assembly: EdmRelationshipAttribute("dstempModel", "dept_emp_ibfk_1", "employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.employee), "dept_emp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.dept_emp), true)]
[assembly: EdmRelationshipAttribute("dstempModel", "dept_manager_ibfk_1", "employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.employee), "dept_manager", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.dept_manager), true)]
[assembly: EdmRelationshipAttribute("dstempModel", "salaries_ibfk_1", "employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.employee), "salaries", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.salary), true)]
[assembly: EdmRelationshipAttribute("dstempModel", "titles_ibfk_1", "employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(dist_sys_ass_2.employee), "titles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(dist_sys_ass_2.title), true)]

#endregion

namespace dist_sys_ass_2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dstempEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dstempEntities1 object using the connection string found in the 'dstempEntities1' section of the application configuration file.
        /// </summary>
        public dstempEntities1() : base("name=dstempEntities1", "dstempEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dstempEntities1 object.
        /// </summary>
        public dstempEntities1(string connectionString) : base(connectionString, "dstempEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dstempEntities1 object.
        /// </summary>
        public dstempEntities1(EntityConnection connection) : base(connection, "dstempEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<department> departments
        {
            get
            {
                if ((_departments == null))
                {
                    _departments = base.CreateObjectSet<department>("departments");
                }
                return _departments;
            }
        }
        private ObjectSet<department> _departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dept_emp> dept_emp
        {
            get
            {
                if ((_dept_emp == null))
                {
                    _dept_emp = base.CreateObjectSet<dept_emp>("dept_emp");
                }
                return _dept_emp;
            }
        }
        private ObjectSet<dept_emp> _dept_emp;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dept_manager> dept_manager
        {
            get
            {
                if ((_dept_manager == null))
                {
                    _dept_manager = base.CreateObjectSet<dept_manager>("dept_manager");
                }
                return _dept_manager;
            }
        }
        private ObjectSet<dept_manager> _dept_manager;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee> employees
        {
            get
            {
                if ((_employees == null))
                {
                    _employees = base.CreateObjectSet<employee>("employees");
                }
                return _employees;
            }
        }
        private ObjectSet<employee> _employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<salary> salaries
        {
            get
            {
                if ((_salaries == null))
                {
                    _salaries = base.CreateObjectSet<salary>("salaries");
                }
                return _salaries;
            }
        }
        private ObjectSet<salary> _salaries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<title> titles
        {
            get
            {
                if ((_titles == null))
                {
                    _titles = base.CreateObjectSet<title>("titles");
                }
                return _titles;
            }
        }
        private ObjectSet<title> _titles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartments(department department)
        {
            base.AddObject("departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dept_emp EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodept_emp(dept_emp dept_emp)
        {
            base.AddObject("dept_emp", dept_emp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dept_manager EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodept_manager(dept_manager dept_manager)
        {
            base.AddObject("dept_manager", dept_manager);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployees(employee employee)
        {
            base.AddObject("employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the salaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosalaries(salary salary)
        {
            base.AddObject("salaries", salary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the titles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotitles(title title)
        {
            base.AddObject("titles", title);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new department object.
        /// </summary>
        /// <param name="dept_no">Initial value of the dept_no property.</param>
        /// <param name="dept_name">Initial value of the dept_name property.</param>
        public static department Createdepartment(global::System.String dept_no, global::System.String dept_name)
        {
            department department = new department();
            department.dept_no = dept_no;
            department.dept_name = dept_name;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_no
        {
            get
            {
                return _dept_no;
            }
            set
            {
                if (_dept_no != value)
                {
                    Ondept_noChanging(value);
                    ReportPropertyChanging("dept_no");
                    _dept_no = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("dept_no");
                    Ondept_noChanged();
                }
            }
        }
        private global::System.String _dept_no;
        partial void Ondept_noChanging(global::System.String value);
        partial void Ondept_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_name
        {
            get
            {
                return _dept_name;
            }
            set
            {
                Ondept_nameChanging(value);
                ReportPropertyChanging("dept_name");
                _dept_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dept_name");
                Ondept_nameChanged();
            }
        }
        private global::System.String _dept_name;
        partial void Ondept_nameChanging(global::System.String value);
        partial void Ondept_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_emp_ibfk_2", "dept_emp")]
        public EntityCollection<dept_emp> dept_emp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dept_emp>("dstempModel.dept_emp_ibfk_2", "dept_emp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dept_emp>("dstempModel.dept_emp_ibfk_2", "dept_emp", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_manager_ibfk_2", "dept_manager")]
        public EntityCollection<dept_manager> dept_manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dept_manager>("dstempModel.dept_manager_ibfk_2", "dept_manager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dept_manager>("dstempModel.dept_manager_ibfk_2", "dept_manager", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="dept_emp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dept_emp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dept_emp object.
        /// </summary>
        /// <param name="emp_no">Initial value of the emp_no property.</param>
        /// <param name="dept_no">Initial value of the dept_no property.</param>
        /// <param name="from_date">Initial value of the from_date property.</param>
        /// <param name="to_date">Initial value of the to_date property.</param>
        public static dept_emp Createdept_emp(global::System.Int32 emp_no, global::System.String dept_no, global::System.DateTime from_date, global::System.DateTime to_date)
        {
            dept_emp dept_emp = new dept_emp();
            dept_emp.emp_no = emp_no;
            dept_emp.dept_no = dept_no;
            dept_emp.from_date = from_date;
            dept_emp.to_date = to_date;
            return dept_emp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_no
        {
            get
            {
                return _emp_no;
            }
            set
            {
                if (_emp_no != value)
                {
                    Onemp_noChanging(value);
                    ReportPropertyChanging("emp_no");
                    _emp_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_no");
                    Onemp_noChanged();
                }
            }
        }
        private global::System.Int32 _emp_no;
        partial void Onemp_noChanging(global::System.Int32 value);
        partial void Onemp_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_no
        {
            get
            {
                return _dept_no;
            }
            set
            {
                if (_dept_no != value)
                {
                    Ondept_noChanging(value);
                    ReportPropertyChanging("dept_no");
                    _dept_no = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("dept_no");
                    Ondept_noChanged();
                }
            }
        }
        private global::System.String _dept_no;
        partial void Ondept_noChanging(global::System.String value);
        partial void Ondept_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime from_date
        {
            get
            {
                return _from_date;
            }
            set
            {
                Onfrom_dateChanging(value);
                ReportPropertyChanging("from_date");
                _from_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("from_date");
                Onfrom_dateChanged();
            }
        }
        private global::System.DateTime _from_date;
        partial void Onfrom_dateChanging(global::System.DateTime value);
        partial void Onfrom_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime to_date
        {
            get
            {
                return _to_date;
            }
            set
            {
                Onto_dateChanging(value);
                ReportPropertyChanging("to_date");
                _to_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("to_date");
                Onto_dateChanged();
            }
        }
        private global::System.DateTime _to_date;
        partial void Onto_dateChanging(global::System.DateTime value);
        partial void Onto_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_emp_ibfk_2", "departments")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_emp_ibfk_2", "departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_emp_ibfk_2", "departments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_emp_ibfk_2", "departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("dstempModel.dept_emp_ibfk_2", "departments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_emp_ibfk_1", "employees")]
        public employee employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_emp_ibfk_1", "employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_emp_ibfk_1", "employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employee> employeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_emp_ibfk_1", "employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employee>("dstempModel.dept_emp_ibfk_1", "employees", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="dept_manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dept_manager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dept_manager object.
        /// </summary>
        /// <param name="dept_no">Initial value of the dept_no property.</param>
        /// <param name="emp_no">Initial value of the emp_no property.</param>
        /// <param name="from_date">Initial value of the from_date property.</param>
        /// <param name="to_date">Initial value of the to_date property.</param>
        public static dept_manager Createdept_manager(global::System.String dept_no, global::System.Int32 emp_no, global::System.DateTime from_date, global::System.DateTime to_date)
        {
            dept_manager dept_manager = new dept_manager();
            dept_manager.dept_no = dept_no;
            dept_manager.emp_no = emp_no;
            dept_manager.from_date = from_date;
            dept_manager.to_date = to_date;
            return dept_manager;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_no
        {
            get
            {
                return _dept_no;
            }
            set
            {
                if (_dept_no != value)
                {
                    Ondept_noChanging(value);
                    ReportPropertyChanging("dept_no");
                    _dept_no = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("dept_no");
                    Ondept_noChanged();
                }
            }
        }
        private global::System.String _dept_no;
        partial void Ondept_noChanging(global::System.String value);
        partial void Ondept_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_no
        {
            get
            {
                return _emp_no;
            }
            set
            {
                if (_emp_no != value)
                {
                    Onemp_noChanging(value);
                    ReportPropertyChanging("emp_no");
                    _emp_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_no");
                    Onemp_noChanged();
                }
            }
        }
        private global::System.Int32 _emp_no;
        partial void Onemp_noChanging(global::System.Int32 value);
        partial void Onemp_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime from_date
        {
            get
            {
                return _from_date;
            }
            set
            {
                Onfrom_dateChanging(value);
                ReportPropertyChanging("from_date");
                _from_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("from_date");
                Onfrom_dateChanged();
            }
        }
        private global::System.DateTime _from_date;
        partial void Onfrom_dateChanging(global::System.DateTime value);
        partial void Onfrom_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime to_date
        {
            get
            {
                return _to_date;
            }
            set
            {
                Onto_dateChanging(value);
                ReportPropertyChanging("to_date");
                _to_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("to_date");
                Onto_dateChanged();
            }
        }
        private global::System.DateTime _to_date;
        partial void Onto_dateChanging(global::System.DateTime value);
        partial void Onto_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_manager_ibfk_2", "departments")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_manager_ibfk_2", "departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_manager_ibfk_2", "departments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("dstempModel.dept_manager_ibfk_2", "departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("dstempModel.dept_manager_ibfk_2", "departments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_manager_ibfk_1", "employees")]
        public employee employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_manager_ibfk_1", "employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_manager_ibfk_1", "employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employee> employeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.dept_manager_ibfk_1", "employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employee>("dstempModel.dept_manager_ibfk_1", "employees", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee object.
        /// </summary>
        /// <param name="emp_no">Initial value of the emp_no property.</param>
        /// <param name="birth_date">Initial value of the birth_date property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="gender">Initial value of the gender property.</param>
        /// <param name="hire_date">Initial value of the hire_date property.</param>
        public static employee Createemployee(global::System.Int32 emp_no, global::System.DateTime birth_date, global::System.String first_name, global::System.String last_name, global::System.String gender, global::System.DateTime hire_date)
        {
            employee employee = new employee();
            employee.emp_no = emp_no;
            employee.birth_date = birth_date;
            employee.first_name = first_name;
            employee.last_name = last_name;
            employee.gender = gender;
            employee.hire_date = hire_date;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_no
        {
            get
            {
                return _emp_no;
            }
            set
            {
                if (_emp_no != value)
                {
                    Onemp_noChanging(value);
                    ReportPropertyChanging("emp_no");
                    _emp_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_no");
                    Onemp_noChanged();
                }
            }
        }
        private global::System.Int32 _emp_no;
        partial void Onemp_noChanging(global::System.Int32 value);
        partial void Onemp_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime birth_date
        {
            get
            {
                return _birth_date;
            }
            set
            {
                Onbirth_dateChanging(value);
                ReportPropertyChanging("birth_date");
                _birth_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birth_date");
                Onbirth_dateChanged();
            }
        }
        private global::System.DateTime _birth_date;
        partial void Onbirth_dateChanging(global::System.DateTime value);
        partial void Onbirth_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime hire_date
        {
            get
            {
                return _hire_date;
            }
            set
            {
                Onhire_dateChanging(value);
                ReportPropertyChanging("hire_date");
                _hire_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hire_date");
                Onhire_dateChanged();
            }
        }
        private global::System.DateTime _hire_date;
        partial void Onhire_dateChanging(global::System.DateTime value);
        partial void Onhire_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_emp_ibfk_1", "dept_emp")]
        public EntityCollection<dept_emp> dept_emp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dept_emp>("dstempModel.dept_emp_ibfk_1", "dept_emp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dept_emp>("dstempModel.dept_emp_ibfk_1", "dept_emp", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "dept_manager_ibfk_1", "dept_manager")]
        public EntityCollection<dept_manager> dept_manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dept_manager>("dstempModel.dept_manager_ibfk_1", "dept_manager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dept_manager>("dstempModel.dept_manager_ibfk_1", "dept_manager", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "salaries_ibfk_1", "salaries")]
        public EntityCollection<salary> salaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<salary>("dstempModel.salaries_ibfk_1", "salaries");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<salary>("dstempModel.salaries_ibfk_1", "salaries", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "titles_ibfk_1", "titles")]
        public EntityCollection<title> titles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<title>("dstempModel.titles_ibfk_1", "titles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<title>("dstempModel.titles_ibfk_1", "titles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="salary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class salary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new salary object.
        /// </summary>
        /// <param name="emp_no">Initial value of the emp_no property.</param>
        /// <param name="salary1">Initial value of the salary1 property.</param>
        /// <param name="from_date">Initial value of the from_date property.</param>
        /// <param name="to_date">Initial value of the to_date property.</param>
        public static salary Createsalary(global::System.Int32 emp_no, global::System.Int32 salary1, global::System.DateTime from_date, global::System.DateTime to_date)
        {
            salary salary = new salary();
            salary.emp_no = emp_no;
            salary.salary1 = salary1;
            salary.from_date = from_date;
            salary.to_date = to_date;
            return salary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_no
        {
            get
            {
                return _emp_no;
            }
            set
            {
                if (_emp_no != value)
                {
                    Onemp_noChanging(value);
                    ReportPropertyChanging("emp_no");
                    _emp_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_no");
                    Onemp_noChanged();
                }
            }
        }
        private global::System.Int32 _emp_no;
        partial void Onemp_noChanging(global::System.Int32 value);
        partial void Onemp_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 salary1
        {
            get
            {
                return _salary1;
            }
            set
            {
                Onsalary1Changing(value);
                ReportPropertyChanging("salary1");
                _salary1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salary1");
                Onsalary1Changed();
            }
        }
        private global::System.Int32 _salary1;
        partial void Onsalary1Changing(global::System.Int32 value);
        partial void Onsalary1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime from_date
        {
            get
            {
                return _from_date;
            }
            set
            {
                if (_from_date != value)
                {
                    Onfrom_dateChanging(value);
                    ReportPropertyChanging("from_date");
                    _from_date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("from_date");
                    Onfrom_dateChanged();
                }
            }
        }
        private global::System.DateTime _from_date;
        partial void Onfrom_dateChanging(global::System.DateTime value);
        partial void Onfrom_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime to_date
        {
            get
            {
                return _to_date;
            }
            set
            {
                Onto_dateChanging(value);
                ReportPropertyChanging("to_date");
                _to_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("to_date");
                Onto_dateChanged();
            }
        }
        private global::System.DateTime _to_date;
        partial void Onto_dateChanging(global::System.DateTime value);
        partial void Onto_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "salaries_ibfk_1", "employees")]
        public employee employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.salaries_ibfk_1", "employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.salaries_ibfk_1", "employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employee> employeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.salaries_ibfk_1", "employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employee>("dstempModel.salaries_ibfk_1", "employees", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dstempModel", Name="title")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class title : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new title object.
        /// </summary>
        /// <param name="emp_no">Initial value of the emp_no property.</param>
        /// <param name="title1">Initial value of the title1 property.</param>
        /// <param name="from_date">Initial value of the from_date property.</param>
        public static title Createtitle(global::System.Int32 emp_no, global::System.String title1, global::System.DateTime from_date)
        {
            title title = new title();
            title.emp_no = emp_no;
            title.title1 = title1;
            title.from_date = from_date;
            return title;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_no
        {
            get
            {
                return _emp_no;
            }
            set
            {
                if (_emp_no != value)
                {
                    Onemp_noChanging(value);
                    ReportPropertyChanging("emp_no");
                    _emp_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_no");
                    Onemp_noChanged();
                }
            }
        }
        private global::System.Int32 _emp_no;
        partial void Onemp_noChanging(global::System.Int32 value);
        partial void Onemp_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title1
        {
            get
            {
                return _title1;
            }
            set
            {
                if (_title1 != value)
                {
                    Ontitle1Changing(value);
                    ReportPropertyChanging("title1");
                    _title1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("title1");
                    Ontitle1Changed();
                }
            }
        }
        private global::System.String _title1;
        partial void Ontitle1Changing(global::System.String value);
        partial void Ontitle1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime from_date
        {
            get
            {
                return _from_date;
            }
            set
            {
                if (_from_date != value)
                {
                    Onfrom_dateChanging(value);
                    ReportPropertyChanging("from_date");
                    _from_date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("from_date");
                    Onfrom_dateChanged();
                }
            }
        }
        private global::System.DateTime _from_date;
        partial void Onfrom_dateChanging(global::System.DateTime value);
        partial void Onfrom_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> to_date
        {
            get
            {
                return _to_date;
            }
            set
            {
                Onto_dateChanging(value);
                ReportPropertyChanging("to_date");
                _to_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("to_date");
                Onto_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _to_date;
        partial void Onto_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onto_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dstempModel", "titles_ibfk_1", "employees")]
        public employee employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.titles_ibfk_1", "employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.titles_ibfk_1", "employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employee> employeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("dstempModel.titles_ibfk_1", "employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employee>("dstempModel.titles_ibfk_1", "employees", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
