//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace dist_sys_ass_2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dataEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dataEntities1 object using the connection string found in the 'dataEntities1' section of the application configuration file.
        /// </summary>
        public dataEntities1() : base("name=dataEntities1", "dataEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dataEntities1 object.
        /// </summary>
        public dataEntities1(string connectionString) : base(connectionString, "dataEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dataEntities1 object.
        /// </summary>
        public dataEntities1(EntityConnection connection) : base(connection, "dataEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<membership> memberships
        {
            get
            {
                if ((_memberships == null))
                {
                    _memberships = base.CreateObjectSet<membership>("memberships");
                }
                return _memberships;
            }
        }
        private ObjectSet<membership> _memberships;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the memberships EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomemberships(membership membership)
        {
            base.AddObject("memberships", membership);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dataModel", Name="membership")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class membership : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new membership object.
        /// </summary>
        /// <param name="membershipId">Initial value of the MembershipId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="membershipClass">Initial value of the MembershipClass property.</param>
        /// <param name="verificationCode">Initial value of the VerificationCode property.</param>
        public static membership Createmembership(global::System.Int32 membershipId, global::System.String firstName, global::System.String lastName, global::System.String membershipClass, global::System.String verificationCode)
        {
            membership membership = new membership();
            membership.MembershipId = membershipId;
            membership.FirstName = firstName;
            membership.LastName = lastName;
            membership.MembershipClass = membershipClass;
            membership.VerificationCode = verificationCode;
            return membership;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipId
        {
            get
            {
                return _MembershipId;
            }
            set
            {
                if (_MembershipId != value)
                {
                    OnMembershipIdChanging(value);
                    ReportPropertyChanging("MembershipId");
                    _MembershipId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MembershipId");
                    OnMembershipIdChanged();
                }
            }
        }
        private global::System.Int32 _MembershipId;
        partial void OnMembershipIdChanging(global::System.Int32 value);
        partial void OnMembershipIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MembershipClass
        {
            get
            {
                return _MembershipClass;
            }
            set
            {
                OnMembershipClassChanging(value);
                ReportPropertyChanging("MembershipClass");
                _MembershipClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MembershipClass");
                OnMembershipClassChanged();
            }
        }
        private global::System.String _MembershipClass;
        partial void OnMembershipClassChanging(global::System.String value);
        partial void OnMembershipClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VerificationCode
        {
            get
            {
                return _VerificationCode;
            }
            set
            {
                OnVerificationCodeChanging(value);
                ReportPropertyChanging("VerificationCode");
                _VerificationCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VerificationCode");
                OnVerificationCodeChanged();
            }
        }
        private global::System.String _VerificationCode;
        partial void OnVerificationCodeChanging(global::System.String value);
        partial void OnVerificationCodeChanged();

        #endregion
    
    }

    #endregion
    
}
